apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mini-lm-embed
  name: mini-lm-embed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mini-lm-embed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mini-lm-embed
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/bharatsahaiyak/ai-tools/mini_lm_embed:dev
          imagePullPolicy: Always
          name: mini-lm-embed
          resources:
            requests:
              memory: "728Mi"
            limits:
              memory: "1024Mi"
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: mini-lm-embed
spec:
  selector:
    app.kubernetes.io/name: mini-lm-embed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mini-lm-embed
spec:
  ingressClassName: kong
  rules:
  - host: "mini-lm-embed.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: mini-lm-embed
            port:
              number: 80
