apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: org-classifier
  name: org-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: org-classifier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: org-classifier
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
          - secretRef:
              name: service-urls
          - secretRef:
              name: service-creds
          image: ghcr.io/bharatsahaiyak/ai-tools/org_classifier:dev
          imagePullPolicy: Always
          name: org-classifier
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: org-classifier
spec:
  selector:
    app.kubernetes.io/name: org-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: org-classifier
spec:
  ingressClassName: kong
  rules:
  - host: "org-classifier.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: org-classifier
            port:
              number: 80
