apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: broadcast-service
  name: broadcast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: broadcast-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: broadcast-service
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
          - secretRef:
              name: broadcast-service
          - secretRef:
              name: service-urls
          - secretRef:
              name: service-creds
          image: ghcr.io/bharatsahaiyak/broadcast-service:dev
          imagePullPolicy: Always
          name: broadcast-service
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: broadcast-service
spec:
  selector:
    app.kubernetes.io/name: broadcast-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: broadcast-service
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/broadcast-service
  destination:
    name: broadcast-service
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: broadcast-service
spec:
  ingressClassName: kong
  rules:
  - host: "broadcast-service.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: broadcast-service
            port:
              number: 80
