apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.discord: |
    url: "WEBHOOK_URL"
    headers:
      - name: Content-Type
        value: application/json

  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "username": "{{.app.metadata.name}}",
            "content": "DISCORD_TAG\n```diff\n+ Application Synced\n```"
          }

  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
        - app-sync-succeeded
      when: app.status.sync.status == 'Synced'

  template.app-health-degraded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "username": "{{.app.metadata.name}}",
            "content": "DISCORD_TAG\n```diff\n- Application Degraded\n```"
          }

  trigger.on-health-degraded: |
    - description: Application is in a degraded or down state
      send:
        - app-health-degraded
      when: app.status.health.status in ['Degraded', 'Failed']
