apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.discord: |
    url: "<YourWebhookUrl>"
    headers:
      - name: Content-Type
        value: application/json

  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "username": "{{.app.metadata.name}}",
            "content": "Application {{.app.metadata.name}} has successfully synced to new version.\\nURL: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
          }

  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
        - app-sync-succeeded
      when: app.status.sync.status == 'Synced'

  template.app-health-degraded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "username": "{{.app.metadata.name}}",
            "content": "Application {{.app.metadata.name}} is currently degraded or down.\\nURL: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}"
          }

  trigger.on-health-degraded: |
    - description: Application is in a degraded or down state
      send:
        - app-health-degraded
      when: app.status.health.status in ['Degraded', 'Failed']