apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kmai-dev
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/kmai-dev
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kmai-stage
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/kmai-stage
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bhasai-dev
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/bhasai-dev
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akai-prod
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/akai-prod
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kmai-prod
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/kmai-prod
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samagra-dev
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/samagra-dev
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rajai-prod
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/rajai-prod
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vistaar-prod
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/vistaar-prod
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
