apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ks-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-health-degraded.discord: ""
    notifications.argoproj.io/subscribe.on-sync-failed.discord: ""
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: ""
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/overlays/ks-prod
    repoURL: 'git@github.com:BharatSahAIyak/k8s.git'
    targetRevision: v2-ks-prod
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true