apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
spec:
  ingressClassName: kong
  rules:
  - host: "admin.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: admin
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-secure
spec:
  ingressClassName: kong
  rules:
  - host: "admin-secure.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: admin
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-tools-proxy
spec:
  rules:
  - host: "ai-tools-proxy.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ai-tools-proxy
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-service
spec:
  rules:
  - host: "auth-service.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: autotune
# spec:
#   rules:
#   - host: "autotune.uat.kumbhsahaiyak.xyz"
    # http:
    #   paths:
    #   - path: /
    #     pathType: ImplementationSpecific
    #     backend:
    #       service:
    #         name: autotune
    #         port:
    #           number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bge-reranker
spec:
  rules:
  - host: "bge-reranker.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bge-reranker
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bge-small-gpu-embeddings
spec:
  rules:
  - host: "bge-small-gpu-embeddings.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bge-small-gpu-embeddings
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataset-service
spec:
  rules:
  - host: "dataset-service.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: dataset-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployer
spec:
  rules:
  - host: "deployer.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: deployer
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: document-service
spec:
  rules:
  - host: "document-service.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: document-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inboundjs
spec:
  ingressClassName: kong
  rules:
  - host: "inboundjs.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: inboundjs
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodehub
spec:
  rules:
  - host: "nodehub.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nodehub
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator
spec:
  rules:
  - host: "orchestrator.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: orchestrator
            port:
              number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: pdf-generator
# spec:
#   rules:
#   - host: "pdf-generator.uat.kumbhsahaiyak.xyz"
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: pdf-parser
# spec:
#   rules:
#   - host: "pdf-parser.uat.kumbhsahaiyak.xyz"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetry
spec:
  rules:
  - host: "telemetry.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: telemetry
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testbed
spec:
  rules:
  - host: "testbed.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: testbed
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transport-socket
spec:
  rules:
  - host: "transport-socket.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: transport-socket
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uci-apis
spec:
  rules:
  - host: "uci-apis.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: uci-apis
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user
spec:
  rules:
  - host: "user.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-management-service
spec:
  rules:
  - host: "user-management-service.uat.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-management-service
            port:
              number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: yt-parser
# spec:
#   rules:
#   - host: "yt-parser.uat.kumbhsahaiyak.xyz"
