resources:
  - ../../base/namespace
  - ../../base/user
  - ../../base/vault-auth
  - ../../base/git-read-token
  - ../../base/app

namespace: kmai-dev

images:
  - name: registry.local/bharatsahaiyak/kisai-bot
    newTag: kmai-dev
  - name: ghcr.io/bharatsahaiyak/pdf-parser
    newTag: 0.5.0

replacements:
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: VaultStaticSecret
      fieldPaths:
      - spec.path
      options:
        delimiter: "/"
        index: 0
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: Ingress
      fieldPaths:
      - spec.rules.0.host
      options:
        delimiter: "."
        index: 1
