apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: asr-mms
  name: asr-mms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: asr-mms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: asr-mms
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
          - secretRef:
              name: asr-mms
          image: ghcr.io/bharatsahaiyak/ai-tools/asr_mms:dev
          imagePullPolicy: Always
          name: asr-mms
          resources:
            requests:
              memory: "5120Mi"
            limits:
              memory: "7200Mi"
              nvidia.com/gpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: asr-mms
spec:
  selector:
    app.kubernetes.io/name: asr-mms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: asr-mms
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/asr-mms
  destination:
    name: asr-mms
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asr-mms
spec:
  ingressClassName: kong
  rules:
  - host: "asr-mms.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: asr-mms
            port:
              number: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-asr-mms
spec:
  containers:
  - name: kaniko-asr-mms
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=$(CONTEXT)"
    - "--destination=$(DESTINATION)"
    envFrom:
      - secretRef:
          name: git-read-token
      - secretRef:
          name: asr-mms
  restartPolicy: Never