apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: asr-mms
  name: asr-mms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: asr-mms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: asr-mms
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/bharatsahaiyak/ai-tools/asr_mms:dev
          imagePullPolicy: Always
          name: asr-mms
          resources:
            requests:
              memory: "4096Mi"
            limits:
              memory: "6144Mi"
              nvidia.com/gpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: asr-mms
spec:
  selector:
    app.kubernetes.io/name: asr-mms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asr-mms
spec:
  ingressClassName: kong
  rules:
  - host: "asr-mms.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: asr-mms
            port:
              number: 80
