apiVersion: v1
kind: Pod
metadata:
  name: kaniko-app
spec:
  containers:
  - name: kaniko-app-builder
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://Ansh-Sarkar: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@github.com/BharatSahAIyak/kisai-bot"
    - "--destination=192.168.0.100:5000/bharatsahaiyak/kisai-bot:dev"
    - "--build-arg=NEXT_PUBLIC_SOCKET_URL=http://ts.k8s.bhasai.samagra.io"
    - "--build-arg=NEXT_PUBLIC_TELEMETRY_API=http://telemetry.k8s.bhasai.samagra.io"
    - "--build-arg=NEXT_PUBLIC_AI_TOOLS_API=http://ai-tools-proxy.k8s.bhasai.samagra.io"
    - "--build-arg=NEXT_PUBLIC_BFF_API_URL=http://bff.k8s.bhasai.samagra.io"
    - "--build-arg=NEXT_PUBLIC_USER_SERVICE_URL=https://uplift-dev-user-service.chatwithpdf.aitools.samagra.io"
    - "--build-arg=NEXT_PUBLIC_USER_SERVICE_APP_ID=7448bd92-b055-477f-b735-e85c145026a7"
    - "--build-arg=NEXT_PUBLIC_BOT_ID=97e60ae3-6fe2-4e30-b259-ee2aee8103ed"
    - "--build-arg=NEXT_PUBLIC_ORG_ID=33ebb23d-0823-4914-b194-475a0642d86b"
  restartPolicy: Never
