apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bm25
  name: bm25
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bm25
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bm25
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/bharatsahaiyak/ai-tools/bm25:dev
          imagePullPolicy: Always
          name: bm25
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: bm25
spec:
  selector:
    app.kubernetes.io/name: bm25
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bm25
spec:
  ingressClassName: kong
  rules:
  - host: "bm25.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bm25
            port:
              number: 80
