apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: default
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-auth
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv
  namespace: default
spec:
  type: kv-v2

  # mount path
  mount: kv

  # path of the secret
  path: env

  # dest k8s secret
  destination:
    name: env-secret
    create: true

  # static secret refresh interval
  refreshAfter: 10s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth