apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: user-management-service
  namespace: default
spec:
  type: kv-v2
  mount: kv
  path: dev/user-management-service
  destination:
    name: user-management-service
    create: true
  refreshAfter: 10s
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth