apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: geoquery
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/geoquery
  destination:
    name: geoquery
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: geoquery
  name: geoquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: geoquery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: geoquery
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: geoquery
          image: ghcr.io/chakshugautam/geoquery.in@sha256:a34c891c4a5339018ead8c9b2efd466315f17127a8d31c141721bf71407d464c
          imagePullPolicy: Always
          name: geoquery
          resources:
            requests:
              memory: "1024Mi"
            limits:
              memory: "1024Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: geoquery
spec:
  selector:
    app.kubernetes.io/name: geoquery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoquery
spec:
  ingressClassName: kong
  rules:
  - host: "geoquery.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: geoquery
            port:
              number: 80
  - host: "geoquery.in"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: geoquery
            port:
              number: 80
  - host: "geoip.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: geoquery
            port:
              number: 80
