apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app.kubernetes.io/name: dataset-service
  name: dataset-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dataset-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dataset-service
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: dataset-service
          image: ghcr.io/bharatsahaiyak/dataset-service:dev
          name: dataset-service
      restartPolicy: Always
