apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv
  namespace: default
spec:
  type: kv-v2
  mount: kv
  path: dev/dataset-service
  destination:
    name: dataset-service
    create: true
  refreshAfter: 10s
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth