resources:
  - ../../base/inboundjs
  - ../../base/pdf-generator
  - ../../base/telemetry
  - ../../base/testbed
  - ../../base/yt-parser
  - ../../base/ai-tools-proxy
  - ../../base/auth-service
  - ../../base/bff
  - ../../base/dataset-service
  - ../../base/deployer
  - ../../base/document-service
  - ../../base/nodehub
  - ../../base/orchestrator
  - ../../base/transport-socket
  - ../../base/uci-apis
  - ../../base/user-management-service
  - ../../base/namespace
  - ../../base/vault-auth
  - ../../base/git-read-token
  - ../../base/admin

namespace: bhasai-stage

images:
  - name: registry.local/bharatsahaiyak/admin
    newTag: bhasai-stage
  - name: ghcr.io/bharatsahaiyak/bff:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/orchestrator:dev
    newTag: 0.6.5 
  - name: ghcr.io/bharatsahaiyak/uci-apis:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/user-management-service
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/transport-socket:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/dataset-service:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/deployer:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/document-service:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/telemetry:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/ai-tools-proxy:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/nodehub:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/inbound-js:dev
    newTag: 0.6.5

replacements:
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: VaultStaticSecret
      fieldPaths:
      - spec.path
      options:
        delimiter: "/"
        index: 0
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: Ingress
      fieldPaths:
      - spec.rules.0.host
      options:
        delimiter: "."
        index: 1
