apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-agri-flow-classifier-bert.yaml
- ingress-agri-flow-classifier-bert.yaml
- service-agri-flow-classifier-bert.yaml
