apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: kmai-dev
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-auth
    serviceAccount: default
    audiences:
      - vault
