apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: telemetry
  namespace: default
spec:
  type: kv-v2
  mount: kv
  path: dev/telemetry
  destination:
    name: telemetry
    create: true
  refreshAfter: 10s
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth