apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ner
  name: ner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ner
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/bharatsahaiyak/ai-tools/ner:dev
          imagePullPolicy: Always
          name: ner
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ner
spec:
  selector:
    app.kubernetes.io/name: ner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ner
spec:
  ingressClassName: kong
  rules:
  - host: "ner.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ner
            port:
              number: 80
