apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: llm-openai-evaluator
  name: llm-openai-evaluator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm-openai-evaluator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm-openai-evaluator
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
          - secretRef:
              name: llm-openai-evaluator
          image: ghcr.io/bharatsahaiyak/ai-tools/llm_openai_evaluator:dev
          imagePullPolicy: Always
          name: llm-openai-evaluator
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: llm-openai-evaluator
spec:
  selector:
    app.kubernetes.io/name: llm-openai-evaluator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: llm-openai-evaluator
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/llm-openai-evaluator
  destination:
    name: llm-openai-evaluator
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-openai-evaluator
spec:
  ingressClassName: kong
  rules:
  - host: "llm-openai-evaluator.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: llm-openai-evaluator
            port:
              number: 80
