apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bm25
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/bm25
  destination:
    name: bm25
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bm25
  name: bm25
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: bm25
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bm25
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
          - secretRef:
              name: bm25
          - secretRef:
              name: service-urls
          - secretRef:
              name: service-creds
          image: ghcr.io/kumbh-sahaiyak/ai-tools/bm25:dev
          imagePullPolicy: Always
          name: bm25
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      imagePullSecrets:
      - name: ks-regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: bm25
spec:
  selector:
    app.kubernetes.io/name: bm25
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bm25
spec:
  ingressClassName: kong
  rules:
  - host: "bm25.stage.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bm25
            port:
              number: 80
