apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
spec:
  template:
    spec:
      containers:
      - name: telemetry
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "2Gi"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
spec:
  ingressClassName: kong
  rules:
  - host: "chatbot.kumbh.up.gov.in"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kumbh-app
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowise
spec:
  ingressClassName: kong
  rules:
  - host: "flowise.prod.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: flowise
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bm25
spec:
  ingressClassName: kong
  rules:
  - host: "bm25.prod.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bm25
            port:
              number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: lipsync
# spec:
#   ingressClassName: kong
#   rules:
#   - host: "lipsync.prod.kumbhsahaiyak.xyz"
#     http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: lipsync
#             port:
#               number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: voice-cloning
# spec:
#   ingressClassName: kong
#   rules:
#   - host: "voice-clone.prod.kumbhsahaiyak.xyz"
#     http:
#       paths:
#       - path: /
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: voice-cloning
#             port:
#               number: 80