apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: rewrite-plugin
    # konghq.com/regex-priority: "1"
  name: user
spec:
  rules:
  - host: "chatbot.kumbh.up.gov.in"
    http:
      paths:
      - path: /user/api/updateUser/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /user/api/sendOTP
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /user/api/login/otp
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /user/api/searchUserByQuery
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /user/api/logout
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /user/api/jwt/verify
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
  - host: "user.prod.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /api/updateUser/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /api/sendOTP
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /api/login/otp
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /api/searchUserByQuery
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /api/logout
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /api/jwt/verify
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: user
            port:
              number: 80