resources:
  - ../../base/pdf-generator
  - ../../base/pdf-parser
  - ../../base/broadcast-service
  - ../../base/org-classifier
  - ../../base/telemetry
  - ../../base/spell-check
  - ../../base/text-translation-azure-dict
  - ../../base/bge-small-gpu-embeddings
  - ../../base/agri-flow-classifier-bert
  - ../../base/llm-openai-evaluator
  - ../../base/asr-mms
  - ../../base/mini-lm-embed
  - ../../base/bm25
  - ../../base/ner
  - ../../base/bge-reranker
  - ../../base/testbed
  - ../../base/autotune
  - ../../base/yt-parser
  - ../../base/ai-tools-proxy
  - ../../base/auth-service
  - ../../base/bff
  - ../../base/dataset-service
  - ../../base/deployer
  - ../../base/document-service
  - ../../base/inboundjs
  - ../../base/nodehub
  - ../../base/orchestrator
  - ../../base/transport-socket
  - ../../base/uci-apis
  - ../../base/user-management-service
  - ../../base/namespace
  - ../../base/vault-auth
  - ../../base/git-read-token
  - ../../base/admin
  - ../../base/agri-flow-classifier-stella  

namespace: bhasai-dev

images:
  - name: registry.local/bharatsahaiyak/admin
    newTag: bhasai-dev
  - name: ghcr.io/bharatsahaiyak/org-classifier:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/bge-reranker:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/bm25:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/bge-small-gpu-embeddings:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/agri-flow-classifier-bert:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/llm-openai-evaluator:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/ner:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/spell-check:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/text-translation-azure-dict:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/asr-mms:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/llm-openai-gpt3:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/agri-flow-classifier-stella:dev
    newTag: 0.6.5

replacements:
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: VaultStaticSecret
      fieldPaths:
      - spec.path
      options:
        delimiter: "/"
        index: 0
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: Ingress
      fieldPaths:
      - spec.rules.0.host
      options:
        delimiter: "."
        index: 1
