resources:
  - ../../base/pdf-generator
  - ../../base/pdf-parser
  - ../../base/broadcast-service
  - ../../base/org-classifier
  - ../../base/telemetry
  - ../../base/spell-check
  - ../../base/text-translation-azure-dict
  - ../../base/bge-small-gpu-embeddings
  - ../../base/agri-flow-classifier-bert
  - ../../base/llm-openai-evaluator
  - ../../base/asr-mms
  - ../../base/mini-lm-embed
  - ../../base/bm25
  - ../../base/ner
  - ../../base/bge-reranker
  - ../../base/testbed
  - ../../base/autotune
  - ../../base/yt-parser
  - ../../base/ai-tools-proxy
  - ../../base/auth-service
  - ../../base/bff
  - ../../base/dataset-service
  - ../../base/deployer
  - ../../base/document-service
  - ../../base/inboundjs
  - ../../base/nodehub
  - ../../base/orchestrator
  - ../../base/transport-socket
  - ../../base/uci-apis
  - ../../base/user-management-service
  - ../../base/namespace
  - ../../base/vault-auth
  - ../../base/git-read-token
  - ../../base/admin
  - ../../base/agri-flow-classifier-stella  

namespace: bhasai-dev

images:
  - name: registry.local/bharatsahaiyak/admin
    newTag: bhasai-dev

replacements:
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: VaultStaticSecret
      fieldPaths:
      - spec.path
      options:
        delimiter: "/"
        index: 0
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: Ingress
      fieldPaths:
      - spec.rules.0.host
      options:
        delimiter: "."
        index: 1
