apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: imd-api
  name: imd-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imd-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imd-api
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
          - secretRef:
              name: imd-api
          image: ghcr.io/vistaar-org/imd-api:dev
          imagePullPolicy: Always
          name: imd-api
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: imd-api
spec:
  selector:
    app.kubernetes.io/name: imd-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: imd-api
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/imd-api
  destination:
    name: imd-api
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imd-api
spec:
  ingressClassName: kong
  rules:
  - host: "imd-api.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: imd-api
            port:
              number: 80
