apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv
  namespace: default
spec:
  type: kv-v2

  # Mount path in Vault
  mount: kv

  # Path of the secret in Vault
  path: test-vault-secrets-operator

  # Destination Kubernetes secret
  destination:
    name: test-vault-secrets-operator
    create: true

  # Static secret refresh interval
  refreshAfter: 10s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth
