apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- VaultStaticSecret-ai-tools-proxy.yml
- deployment-ai-tools-proxy.yaml
- ingress-ai-tools-proxy.yaml
- service-ai-tools-proxy.yaml
