# This secret is utilised in Kaniko to pull the code of repositories to be able to build images

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: git-read-token
spec:
  type: kv-v2
  mount: kv
  path: git-read-token
  destination:
    name: git-read-token
    create: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  refreshAfter: 10s
  vaultAuthRef: static-auth