apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app.kubernetes.io/name: transport-socket
  name: transport-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transport-socket
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transport-socket
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: transport-socket
          image: ghcr.io/bharatsahaiyak/transport-socket:dev
          name: transport-socket
      restartPolicy: Always
