apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin
  namespace: default
spec:
  type: kv-v2
  mount: kv
  path: dev/admin
  destination:
    name: admin
    create: true
  refreshAfter: 10s
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: static-auth