apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bff
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: bff
          - secretRef:
              name: service-urls
          - secretRef:
              name: service-creds
          image: ghcr.io/kumbh-sahaiyak/bff:bhashini_feature
          imagePullPolicy: Always
          name: bff
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
      imagePullSecrets:
      - name: ks-regcred
