apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bff
spec:
  ingressClassName: kong
  rules:
  - host: "bff.stage.kumbhsahaiyak.xyz"
    http:
      paths:
      - path: /pwa/tts/initiate
        pathType: ImplementationSpecific
        backend:
          service:
            name: bff
            port:
              number: 80
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bff
            port:
              number: 80
