resources:
  - ../../base/inboundjs
  # - ../../base/pdf-generator
  - ../../base/telemetry
  - ../../base/testbed
  # - ../../base/yt-parser
  - ../../base/ai-tools-proxy
  - ../../base/auth-service
  - ../../base/kumbh/bff
  - ../../base/kumbh/api_plugin
  - ../../base/dataset-service
  - ../../base/bge-small-gpu-embeddings
  - ../../base/bge-reranker
  - ../../base/deployer
  - ../../base/document-service
  - ../../base/nodehub
  - ../../base/orchestrator
  - ../../base/transport-socket
  - ../../base/uci-apis
  - ../../base/user-management-service
  - ../../base/user
  - ../../base/namespace
  - ../../base/vault-auth
  - ../../base/common-secrets
  - ../../base/git-read-token
  - ../../base/admin
  - ../../base/kumbh/app
  # - ../../base/kumbh/lipsync
  - ../../base/kumbh/flowise
  # - ../../base/kumbh/voice_cloning
  - ../../base/kumbh/bm25
  - ../../base/kumbh/geoquery
  - ../../base/kumbh/telemetry_reliability_auto_tagger
  - ../../base/kumbh/html-to-pdf

namespace: ks-stage

images:
  - name: registry.local/bharatsahaiyak/admin
    newTag: ks-stage
  - name: registry.local/kumbhsahaiyak/app
    newTag: ks-stage
  # - name: registry.local/kumbhsahaiyak/voice_cloning
  #   newTag: ks-stage
  - name: registry.local/kumbhsahaiyak/flowise
    newTag: ks-stage
  - name: ghcr.io/kumbh-sahaiyak/bff:dev
    newTag: stage
  # - name: ghcr.io/kumbh-sahaiyak/lipsync:dev
  #   newTag: main
  - name: ghcr.io/bharatsahaiyak/orchestrator:dev
    newTag: 0.7.0-hotfix-7
  - name: ghcr.io/bharatsahaiyak/uci-apis:dev
    newTag: 0.7.0-hotfix-1
  - name: ghcr.io/bharatsahaiyak/user-management-service
    newTag: 0.6.5-hotfix-1
  - name: samagragovernance/esamwad-user-service
    newName: ghcr.io/samagra-development/user-service
    newTag: master
  - name: ghcr.io/bharatsahaiyak/transport-socket:dev
    newTag: 0.7.0-hotfix-2
  - name: ghcr.io/bharatsahaiyak/dataset-service:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/deployer:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/document-service:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/telemetry:dev
    newTag: 0.7.0-hotfix-9
  - name: ghcr.io/bharatsahaiyak/ai-tools-proxy:dev
    newTag: 0.7.0-hotfix-1
  - name: ghcr.io/bharatsahaiyak/nodehub:dev
    newTag: 0.6.5
  - name: ghcr.io/bharatsahaiyak/inbound-js:dev
    newTag: 0.7.1-uat-2
  - name: ghcr.io/kumbh-sahaiyak/ai-tools/bm25:dev
    newTag: main

replacements:
- source:
    kind: Namespace
    fieldPath: metadata.name
  targets:
    - select:
        kind: VaultStaticSecret
      fieldPaths:
      - spec.path
      options:
        delimiter: "/"
        index: 0
# - source:
#     kind: Namespace
#     fieldPath: metadata.name
#   targets:
#     - select:
#         kind: Ingress
#       fieldPaths:
#       - spec.rules.0.host
#       options:
#         delimiter: "."
#         index: 1

patches:
- path: patch.yaml
- path: bff-patch.yaml

# patchesStrategicMerge:
# - scaling-patch.yaml