apiVersion: v1
kind: Service
metadata:
  name: {{APPLICATION}}
spec:
  selector:
    app.kubernetes.io/name: {{APPLICATION}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{TARGET_PORT}}