apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{APPLICATION}}
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/{{APPLICATION}}
  destination:
    name: {{APPLICATION}}
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth