apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dataset-service
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/dataset-service
  destination:
    name: dataset-service
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dataset-service
  name: dataset-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dataset-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dataset-service
    spec:
      containers:
        - envFrom:
          - secretRef:
              name: dataset-service
          image: ghcr.io/bharatsahaiyak/dataset-service:dev
          name: dataset-service
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dataset-service
spec:
  selector:
    app.kubernetes.io/name: dataset-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataset-service
spec:
  ingressClassName: kong
  rules:
  - host: "dataset-service.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: dataset-service
            port:
              number: 80
