apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spell-check
  name: spell-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spell-check
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spell-check
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
          - secretRef:
              name: service-urls
          - secretRef:
              name: service-creds
          image: ghcr.io/bharatsahaiyak/ai-tools/spell_check:dev
          imagePullPolicy: Always
          name: spell-check
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: spell-check
spec:
  selector:
    app.kubernetes.io/name: spell-check
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spell-check
spec:
  ingressClassName: kong
  rules:
  - host: "spell-check.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: spell-check
            port:
              number: 80
