---
- name: Setup kubeconfig file
  hosts: localhost
  gather_facts: true
  vars:
    username: "ubuntu"
    local_kubeconfig_path: "~/tmp-kubespray.conf"
    control_plane: "{{ groups['kube_control_plane'] | map('extract', hostvars, ['ansible_host']) | list | first }}"

  tasks:
    - name: Copy kubeconfig file from the controller node
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ local_kubeconfig_path }}"
        flat: true
      delegate_to: "{{ control_plane }}"
      become: true

    - name: Replace internal IP with external IP in kubeconfig
      ansible.builtin.replace:
        path: "{{ local_kubeconfig_path }}"
        regexp: 'server: https://127.0.0.1:6443'
        replace: 'server: https://{{ control_plane }}:6443'

    - name: Export KUBECONFIG environment variable
      ansible.builtin.shell: |
        set -ex
        export KUBECONFIG={{ local_kubeconfig_path }}
        mkdir -p ~/.kube
        kubectl config view --flatten > ~/.kube/config
      args:
        executable: /bin/bash
      changed_when: true
