apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- admin
- ai-tools
- ai-tools-proxy
# - app
- auth-service
- bff
- dataset-service
# - demo-org
- deployer
- document-service
# - flowise
- inboundjs
# - kaniko
- orchestrator
- telemetry
- transport-socket
- uci-apis
- user-management-service
