apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pdf-generator
  name: pdf-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pdf-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pdf-generator
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
          - secretRef:
              name: pdf-generator
          - secretRef:
              name: service-urls
          - secretRef:
              name: service-creds
          image: ghcr.io/bharatsahaiyak/pdf-generator:dev
          imagePullPolicy: Always
          name: pdf-generator
          resources:
            requests:
              memory: "2048Mi"
            limits:
              memory: "2048Mi"
      
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-generator
spec:
  selector:
    app.kubernetes.io/name: pdf-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pdf-generator
spec:
  type: kv-v2
  mount: kv
  path: NAMESPACE/pdf-generator
  destination:
    name: pdf-generator
    create: true
  refreshAfter: 10s
  vaultAuthRef: static-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-generator
spec:
  ingressClassName: kong
  rules:
  - host: "pdf-generator.NAMESPACE.k8s.bhasai.samagra.io"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: pdf-generator
            port:
              number: 80
