name: Generate Application Configuration

on:
  workflow_dispatch:
    inputs:
      application:
        description: 'Application name'
        required: true
      replicas:
        description: 'Number of replicas'
        required: true
      target_port:
        description: 'Target port'
        required: true
      image_url:
        description: 'Docker image URL'
        required: true
      env_vars:
        description: 'Space-separated environment variables (e.g., dev staging)'
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate configuration files
      run: |
        APP=${{ github.event.inputs.application }}
        REPLICAS=${{ github.event.inputs.replicas }}
        TARGET_PORT=${{ github.event.inputs.target_port }}
        IMAGE_URL=${{ github.event.inputs.image_url }}
        ENV_VARS=${{ github.event.inputs.env_vars }}

        # Create the APPLICATION directory
        mkdir -p "base/$APP"

        # Replace placeholders in the template and create application.yaml
        envsubst < templates/application.yaml > "base/$APP/application.yaml"

        # Create overlay directories and files
        for ENV in $ENV_VARS; do
          mkdir -p "overlays/$ENV"

          # Create kustomization.yaml
          cat <<EOF > "overlays/$ENV/kustomization.yaml"
resources:
- ../../base/$APP/application.yaml
EOF
        done
